baseURL = "https://appraisily.com"
languageCode = "en-us"
title = "Appraisily - Antique & Art Valuation"
enableRobotsTXT = true
enableGitInfo = true

[params]
  description = "Expert antique and art valuation services with instant online screening"
  author = "Appraisily"
  images = ["images/default-social.jpg"]

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5

[markup.goldmark.renderer]
  unsafe = true

[minify]
  minifyOutput = true

[permalinks]
  blog = "/blog/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"
  keyword = "keywords"