[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.121.1"
  GO_VERSION = "1.21.5"

[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 200

[[headers]]
  for = "/admin/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "@netlify/plugin-sitemap"

[plugins.inputs.sitemap]
  buildDir = "public"
  exclude = ['/admin/*']

[context.production]
  command = "hugo --gc --minify"
  [context.production.environment]
    HUGO_ENV = "production"

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' https://identity.netlify.com https://unpkg.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://identity.netlify.com;"

[[headers]]
  for = "/*.js"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/*.css"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/images/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

[context.deploy-preview]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"