backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Last Modified", name: "lastmod", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Keywords", name: "keywords", widget: "list"}
      - {label: "Tags", name: "tags", widget: "list", default: ["antiques", "valuation"]}
      - {label: "Categories", name: "categories", widget: "list", default: ["Antiques"]}
      - {label: "Author", name: "author", widget: "string", default: "Appraisily"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "SEO Title", name: "seo_title", widget: "string", required: false}
      - {label: "Meta Description", name: "description", widget: "text", pattern: ['.{50,160}', "Must be between 50 and 160 characters"]}
      - {label: "Canonical URL", name: "canonical", widget: "string", required: false}
      - {label: "No Index", name: "noindex", widget: "boolean", default: false}
      - {label: "Structured Data", name: "schema", widget: "object", fields: [
          {label: "Type", name: "type", widget: "select", options: ["BlogPosting", "Article", "Product"]},
          {label: "Review Rating", name: "rating", widget: "number", required: false, min: 1, max: 5, step: 0.1}
        ]}
      - {label: "Body", name: "body", widget: "markdown"}